/// The currency code supported by the Euro Reference.
public enum AsyncEuroReferenceCurrencyCode: String, Codable, CaseIterable, Sendable {
  case euro = "EUR"
  case americanDollar = "USD"
  case japaneseYen = "JPY"
  case bulgarianLev = "BGN"
  case czechKoruna = "CZK"
  case danishKrone = "DKK"
  case sterling = "GBP"
  case hungarianForint = "HUF"
  case polishZloty = "PLN"
  case romanianLeu = "RON"
  case swedishKrona = "SEK"
  case swissFranc = "CHF"
  case icelandicKrona = "ISK"
  case norwegianKrone = "NOK"
  case turkishLira = "TRY"
  case australianDollar = "AUD"
  case brazilianReal = "BRL"
  case canadianDollar = "CAD"
  case renminbi = "CNY"
  case hongKongDollar = "HKD"
  case indonesianRupiah = "IDR"
  case israeliNewShekel = "ILS"
  case southKoreanWong = "KRW"
  case mexicanPeso = "MXN"
  case malaysianRinggit = "MYR"
  case newZealandDollar = "NZD"
  case philippinePeso = "PHP"
  case singaporeDollar = "SGD"
  case thaiBaht = "THB"
  case southAfricanRand = "ZAR"
}
